### ISSUE TITLE
Enable Travis CI

### ISSUE THREAD

**Issue by Jimbly** [creationix/http-parser-js#19]
@creationix I'd like to enable Travis CI on this project so we get tests ran on PRs and it can be configured to automatically publish to NPM after merging PRs.  I think all you need to do is go to https://travis-ci.org and click the switch to enable it for this project, and I should have access after that is done.

**Comment by creationix** [comment]
ok, I've enabled it, let me know if you need anything else.

**Comment by Jimbly** [comment]
Seems to be working, thanks.  Sounds like automatic NPM publishing has issues with Travis CI, so for now just using it to auto-run our tests on any PRs.

**Comment by creationix** [comment]
awesome.  Thanks for taking care of the library.

**Comment by Jimbly** [comment]
No problem!  We were actively using it for a while at my job at Yahoo (because of some legacy servers that served such malformed URL that Node would crash ;), and now it's just become something slightly interesting ^_^.  I just open-sourced [our memcached binary client](https://github.com/yahoo/memcached-binary) and Yahoo uses Travis CI for all of their open source Node stuff, and it was so simple to get tests running I figured I should enable that on my own projects =), especially since (thanks to Jan) this one has so many tests =).
