### ISSUE TITLE
Any known issues?

### ISSUE THREAD

**Issue by umutm** [creationix/http-parser-js#20]
First of all, thanks for creating http-parser.

We are using Node HTTP heavily to send requests to many different URLs and planning to use http-parser-js for tolerating corrupted headers.

I wanted to ask if there are any known issues with the module (like performance or parsing issues in some cases)?

Thanks very much.

**Comment by Jimbly** [comment]
From all those involved, you're welcome!

As far as I know, there are no known issues (I guess that's the definition of "known"...).  Parsing wise it, last time it was updated, passes all tests that Node's HTTP parser passes, plus a few additional ones for tolerating corrupt headers.

No idea on performance, though I seem to remember some simple tests (before this was as robust, so take them with a grain of salt) indicating it was faster than the native parser.  If you have any benchmarks, I'd be curious to see how it does swapping it, it's just 1 line of code at startup to try!

If you run into any issues with additional kinds of corrupted headers, we'll happily accept any PR to deal with them, and I can point you to some examples of how to add a simple test to ensure that kind of corrupt header is continually handled in future versions.

**Comment by umutm** [comment]
Thanks very much for the update.

If I can collect performance data, will definitely be sharing it here.
