### ISSUE TITLE
Getting a "parse error" on a URL

### ISSUE THREAD

**Issue by umutm** [creationix/http-parser-js#32]
We use http-parser for sending requests to 1000s of websites and it works great.

An exception is, sending HTTP requests to: http://mod_s.tessellateos.com/ . It returns "parse error" again (tested with node v4.4.2).

Any ideas why it can't ignore the parse error?

**Comment by creationix** [comment]
Do you get any errors when using node's native http parser?

**Comment by umutm** [comment]
Sorry for my delay.

I was getting a parse error too.

Yet, it seems like something has changed in the website and the issue doesn't exist anymore. I'm closing this issue now and will be re-opening if I ever face it again.

Sorry for taking your time.
