### ISSUE TITLE
While running flow in a project: Unexpected end of input Found 1 error

### ISSUE THREAD

**Issue by dbertella** [creationix/http-parser-js#39]
I keep getting this error while running flow in my project.
```
Error: node_modules/http-parser-js/package.json:1
  1: {
     ^ Unexpected end of input


Found 1 error
```

I simply replaced non ascii characters (**ä**, **ü**) from the package json and flow isn't complaining anymore.
```
    "Jan Schär (https://github.com/jscissr)",
    "Paul Rütter (https://github.com/paulrutter)"
```

Is anybody else not having this problem?
This is my dependencies tree if can be any help:
```
└─┬ react-dev-utils@3.1.1
  └─┬ sockjs-client@1.1.4
    └─┬ faye-websocket@0.11.1
      └─┬ websocket-driver@0.7.0
        └── http-parser-js@0.4.5
```

**Comment by Jimbly** [comment]
This is worked around on our side in http-parser-js@0.4.6, there's also an open issue over at Flow: https://github.com/facebook/flow/issues/4867
