### ISSUE TITLE
http-parser tests ported to js

### ISSUE THREAD

**Issue by mscdex** [creationix/http-parser-js#6]
I wanted to let you all know that I have recently ported [joyent/http-parser's tests to js](https://github.com/mscdex/io.js/blob/js-http-parser/test/parallel/test-http-parser-durability.js), however there are some tweaks that you will need to make since the js http parser I used in the ported tests has a slightly different API.

The ported tests do not include *everything* though, such as the http method tests and tests for things like `pause()`/`resume()` and LF-only line endings.

**Comment by jscissr** [comment]
The link now returns a 404 page. Was the test renamed or moved?

**Comment by mscdex** [comment]
It was moved to the `pummel` tests [here](https://github.com/mscdex/io.js/blob/js-http-parser/test/pummel/test-http-parser-durability.js).

**Comment by Jimbly** [comment]
Thank you for the info on the tests, and thanks @jscissr for merging them and getting this module passing nearly all of them!
