### ISSUE TITLE
Not working on node13 with request module

### ISSUE THREAD

**Issue by voxsoftware** [creationix/http-parser-js#68]
Monkey path not working on node13 with request module. 
Still getting error HPE_INVALID_HEADER_TOKEN , so I assume that still using internal module

**Comment by Jimbly** [comment]
What Node version exactly?  Also, have a simple example?  HPE_INVALID_HEADER_TOKEN sounds like Node v11, but maybe that's still in there somewhere...

**Comment by voxsoftware** [comment]
IN node 13.1.0
Is only a request to a gobernment website

**Comment by Jimbly** [comment]
I'm not seeing any problems with Node v13.1.0 here, though it did just release yesterday.  Are you absolutely sure you're monkey-patching before *anything* is requiring http, or any other internal Node module?

**Comment by Jimbly** [comment]
Works with current Node v13 and v14 now.
