### ISSUE TITLE
timeout event listener registration error

### ISSUE THREAD

**Issue by emarteca** [creationix/http-parser-js#69]
Hi all, I've been working on a tool to identify instances of events registered to the wrong object in uses of some JavaScript event-driven APIs, as part of a research project.
The tool flagged [line 155](https://github.com/creationix/http-parser-js/blob/master/tests/parallel/test-http-set-timeout-server.js#L155) in tests/parallel/test-http-set-timeout-server.js, on the registration of the “timeout” event.

The reason I believe this is indicative of an error is as follows (from looking at the [nodejs http API documentation](https://nodejs.org/api/http.html#http_http_createserver_options_requestlistener):
The req variable, as the first argument to the callback of createServer (on [line 154](https://github.com/creationix/http-parser-js/blob/master/tests/parallel/test-http-set-timeout-server.js#L154)), is an object of type http.IncomingMessage. However, the “timeout” event is not emitted on http.IncomingMessage. 

Since the name “req” implies that this variable should be a request, my guess is that the author of this code thought that req was an object of type http.ClientRequest, where “timeout” is actually emitted. 
For example, in [another location in the testing code](https://github.com/creationix/http-parser-js/blob/master/tests/parallel/test-http-client-timeout-event.js#L31) there is a registration of a listener for “timeout” on another variable called req, but this one is actually an http.ClientRequest, since it is the result of [a call to http.request](https://github.com/creationix/http-parser-js/blob/master/tests/parallel/test-http-client-timeout-event.js#L19).

Thanks!

**Comment by Jimbly** [comment]
Thanks!

The tests here are just a copy of the ones in Node proper, and [they're also registering this event](https://github.com/nodejs/node/blob/master/test/parallel/test-http-set-timeout-server.js#L194), however, the test is specifically testing that a `timeout` event is *not* emitted, so I think everything's fine, even if it's an unnecessary assertion.

**Comment by emarteca** [comment]
Ah ok that makes sense, thanks for looking into it and letting me know! :)
