### ISSUE TITLE
Create new release of `http-parser-js` now you've fixed up Node 16 tests

### ISSUE THREAD

**Issue by HonkingGoose** [creationix/http-parser-js#82]
Might be nice to cut a new release, because the version on `master` now works on Node 16, but these changes are not present in the published package on npm. Node 16 will become LTS soon, so might be nice to release a "Node 16 supported" version of the package, so that users can try it out ahead of time?

Just a suggestion, feel free to close this issue if you don't want/aren't ready to make a new release. 😉

**Comment by Jimbly** [comment]
The changes were entirely limited to the tests, which are not included in the npm release, so there is nothing to publish.  The version that's published to npm should work on Node 16.
