### ISSUE TITLE
maxHeaderSize  It should be an instance property, not a static property of the constructor.

### ISSUE THREAD

**Issue by masx200** [creationix/http-parser-js#93]
maxHeaderSize  It should be an instance property, not a static property of the constructor.

https://github.com/creationix/http-parser-js/blob/8a13b79e0d9ddadbb0997eaf3d375aa5bc89e0f1/http-parser.js#L33

**Comment by masx200** [comment]
https://nodejs.org/dist/latest-v18.x/docs/api/http.html#httpmaxheadersize

This can be overridden for servers and client requests by passing the maxHeaderSize option.

**Comment by masx200** [comment]
https://github.com/creationix/http-parser-js/blob/8a13b79e0d9ddadbb0997eaf3d375aa5bc89e0f1/http-parser.js#L138

**Comment by Jimbly** [comment]
I suspect it needs to be _both_ to keep compatibility with both old users and the new Node API.

**Comment by masx200** [comment]
> I suspect it needs to be _both_ to keep compatibility with both old users and the new Node API.

```js
 if  ( this . headerSize  > (this.maxHeaderSize || HTTPParser . maxHeaderSize ))  {
```
