### ISSUE TITLE
[Question] Supports for Node 15 or higher?

### ISSUE THREAD

**Issue by shotat** [creationix/http-parser-js#97]
Hi, I have a question.
Is there any way to get this great library to work with Node.js 15 or higher?
It would be helpful if we could use this library with the latest node versions.

**Comment by Jimbly** [comment]
Generally works on Node 16.x (that's in the testing suite tested against).  Trying locally all tests pass on `v16.13.0` which I've got installed, though seem to break on `v16.19.1`, maybe something broke in between there.  If someone can track down what version/Node.js change caused it, perhaps it can be worked around, but for now might just need to use a slightly older minor version.

**Comment by shotat** [comment]
Thanks!
